# Generated by Django 4.1.2 on 2022-10-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
