# Generated by Django 4.1.2 on 2022-10-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_token_called'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
